// <auto-generated />
using System;
using AspireApp1.ApiService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AspireApp1.ApiService.Migrations
{
    [DbContext(typeof(RentalDbContext))]
    [Migration("20260428150112_AddEstAnnuleToLocation")]
    partial class AddEstAnnuleToLocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AspireApp1.ApiService.Domain.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("loc_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loc_datedebut");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loc_datefin");

                    b.Property<bool>("EstAnnule")
                        .HasColumnType("boolean")
                        .HasColumnName("loc_annule");

                    b.Property<int>("LoueurId")
                        .HasColumnType("integer")
                        .HasColumnName("lou_id");

                    b.Property<int>("VoitureId")
                        .HasColumnType("integer")
                        .HasColumnName("voi_id");

                    b.HasKey("Id");

                    b.HasIndex("LoueurId");

                    b.HasIndex("VoitureId");

                    b.ToTable("t_j_location_loc");
                });

            modelBuilder.Entity("AspireApp1.ApiService.Domain.Loueur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("lou_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cp")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("lou_cp");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("lou_mobile");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lou_nom");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lou_pays");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lou_prenom");

                    b.Property<string>("Rue")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lou_rue");

                    b.Property<string>("Ville")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lou_ville");

                    b.HasKey("Id");

                    b.HasIndex("Mobile")
                        .IsUnique();

                    b.ToTable("t_e_loueur_lou");
                });

            modelBuilder.Entity("AspireApp1.ApiService.Domain.Voiture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("voi_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("voi_categorie");

                    b.Property<string>("Immatriculation")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("voi_immatriculation");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("voi_marque");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("voi_modele");

                    b.Property<decimal>("PrixLocationParJour")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("voi_prixlocationparjour");

                    b.HasKey("Id");

                    b.ToTable("t_e_voiture_voi");
                });

            modelBuilder.Entity("AspireApp1.ApiService.Domain.Location", b =>
                {
                    b.HasOne("AspireApp1.ApiService.Domain.Loueur", "Loueur")
                        .WithMany()
                        .HasForeignKey("LoueurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspireApp1.ApiService.Domain.Voiture", "Voiture")
                        .WithMany()
                        .HasForeignKey("VoitureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loueur");

                    b.Navigation("Voiture");
                });
#pragma warning restore 612, 618
        }
    }
}
